captainVersion: 4
services:
  $$cap_appname:
    image: roundcube/roundcubemail:$$cap_version
    volumes:
      - $$cap_appname-data-html:/var/www/html
    restart: always
    ports:
      - '8000:80' 
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: $$cap_host_name
      ROUNDCUBEMAIL_SMTP_SERVER: $$cap_host_name
      ROUNDCUBEMAIL_DEFAULT_PORT: $$cap_default_port
      ROUNDCUBEMAIL_SMTP_PORT: $$cap_smtp_port
      ROUNDCUBEMAIL_DB_TYPE: pgsql
      ROUNDCUBEMAIL_DB_HOST: srv-captain--$$cap_appname-db
      ROUNDCUBEMAIL_DB_PORT: 5432
      ROUNDCUBEMAIL_DB_USER: $$cap_db_user
      ROUNDCUBEMAIL_DB_PASSWORD: $$cap_db_pass
      ROUNDCUBEMAIL_DB_NAME: $$cap_db_name
    caproverExtra:
    depends_on:
      - $$cap_appname-db
    containerHttpPort: 8000 

  # Postgres
  $$cap_appname-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: $$cap_db_user
      POSTGRES_DB: $$cap_db_name
      POSTGRES_PASSWORD: $$cap_db_pass
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: 'true'

caproverOneClickApp:
    variables:
      - id: $$cap_version
        label: Roundcube
        description: Choose the latest version of Roundcube Server from https://hub.docker.com/r/roundcube/roundcubemail/tags
        defaultValue: 1.6.6-apache

      - id: $$cap_host_name
        label: Hostname of the IMAP server to connect to. For encypted connections, prefix the host with tls:// (STARTTLS) or ssl:// (SSL/TLS).
        defaultValue: mail

      - id: $$cap_default_port
        label: IMAP port number;
        defaultValue: 143

      - id: $$cap_smtp_port
        label: SMTP port number
        defaultValue: 587

      - id: $$cap_db_user
        label: Postgres database user
        defaultValue: roundcube
        description: Enter a user for database

      - id: $$cap_db_name
        label: Postgres database name
        defaultValue: roundcube_db
        description: Enter a databse name

      - id: $$cap_db_pass
        label: Postgres database password
        defaultValue: $$cap_gen_random_hex(24)
        description: Enter database password
    instructions:
      start: |-
          Build Roundcube mail client
      end: |-
          Roundcube has been successfully deployed!
          Your service is available at https://$$cap_appname.$$cap_root_domain
    displayName: Roundcube
    isOfficial: true
    description: Browser-based IMAP client with an application-like user interface.